### ISSUE TITLE
Node replication checklist

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/heartwood#274]
A few important items to get right before we can release:

* [x] Worker replication does not handle failures gracefully. This is because there's no way to properly communicate replication failure currently.
* [x] We need to switch over to NoiseXK handshake pattern, from NoiseNN
* [x] ~~We need some kind of sync command that can be run after patch/issue creation, which is just a wrapper around `announce-refs`~~
* [x] #365
* [x] We need to run `announce-refs` when `rad init` is called, so that new projects can be announced on the network without a node restart. For this to work, `announce-refs` should be able to update inventories as well.
* [x] #364
* [x] Socket file should be deleted on Ctrl-C
